###############################################################################################
# clipi shortcut toml #
###############################################################################################

# run:

'Cleanup...' = true
