###############################################################################################
# clipi shortcut toml
###############################################################################################

'Cleanup...' = true
