###############################################################################################
# clipi shortcut toml
###############################################################################################

'Launch a Pi emulation' = true
'use64' = true

'image' = 'debian_daily'
'kernel' = 'bin/ddebian/vmlinuz-4.19.0-9-arm64'
'initrd' = 'bin/ddebian/initrd.img-4.19.0-9-arm64'

'bridge' = true

'network' = """
-netdev bridge,br=br0,id=net0 \
-device virtio-net-pci,netdev=net0
"""

'**args' = """
-device virtio-blk-device,drive=hd-root \
-no-reboot -monitor stdio
"""