###############################################################################################
# clipi shortcut toml
###############################################################################################

# (particularly for 32 bit guests) you'll probably want to supply a specific kernel,
# like strech for versatilepb:
bin = "bin/kernel-qemu-4.14.79-stretch"
# or:
# bin = "bin/kernel-qemu-4.14.79-stretch"

qcow_size = "+8G"  # expanded virtual volume size

device32 = 'versatilepb'
mem_vers = "256"  # versatilepb doesn"t support over 256M
cpu32 = "arm1176"


device64 = 'virt'
initrd64 = 'bin/ddebian/initrd.img-4.19.0-9-arm64'

# normal arm -virt devices are not restricted for memory,
# unlike qemu methods for ARMv6 (256M) and raspi3 ARMv8 (1G).
mem_64 = "2048"
aarch64 = "aarch64"
cpu64 = "cortex-a53"

