###############################################################################################
# clipi shortcut toml
###############################################################################################

'Find Pi devices on this network' = true

