###############################################################################################
# clipi shortcut toml #
###############################################################################################

# run:

'Find Pi devices on this network' = true

