###############################################################################################
# clipi shortcut toml #
###############################################################################################

# run:

'Launch a Pi emulation' = true
'image' = 'Pi64_OS_Beta'
'use64' = true

