###############################################################################################
# clipi shortcut toml
###############################################################################################

'Launch a Pi emulation' = true
'image' = 'dietpi'
