###############################################################################################
# clipi shortcut toml
###############################################################################################

'Launch a Pi emulation' = true
'image' = 'buster_desktop'

###############################################################################################
# defaults #
###############################################################################################

# qemu:
bin = "bin/kernel-qemu-4.14.79-stretch"
qcow_size = "+8G"
mem_vers = "256"  # versatilepb doesn't support over 256M
cpu32 = "arm1176"

