###############################################################################################
# clipi shortcut toml #
###############################################################################################

# run:

'Launch a Pi emulation' = true
'image' = 'buster_desktop'
'use64' = true  # optional 'true' uses aarch64 w/ cortex-a53- bootstrap install, needs extra attention during setup

###############################################################################################
# defaults #
###############################################################################################

# qemu:
qcow_size = "+8G"
mem_64 = "2048"
aarch64 = "aarch64"
cpu64 = "cortex-a53"
