###############################################################################################
# clipi shortcut toml #
###############################################################################################

# run:

'Launch a Pi emulation' = true
'image' = 'stretch_lite'


###############################################################################################
# defaults #
###############################################################################################

# qemu:
bin = "bin/kernel-qemu-4.14.79-stretch"
qcow_size = "+8G"
mem_vers = "256"  # versatilepb doesn"t support over 256
aarch32 = "aarch32"
cpu32 = "arm1176"

