###############################################################################################
# clipi shortcut toml
###############################################################################################

'Launch a Pi emulation' = true
'image' = 'dietpi'

###############################################################################################
# defaults #
###############################################################################################

# qemu:
bin = "bin/kernel-qemu-4.14.79-stretch"
qcow_size = "+8G"
mem_vers = "256"  # versatilepb doesn"t support over 256
cpu32 = "arm1176"

