###############################################################################################
# clipi shortcut toml #
###############################################################################################

# run:

# 'Launch a Pi emulation' = true
# 'image' = 'retropie'

# set up guest with:
#$ sudo chmod u+x RetroPie-Setup/retropie_setup.sh
#$ sudo __platform=rpi3 ./RetroPie-Setup/retropie_setup.sh
