###############################################################################################
#
# locations, names for image / iso files
#
# feel free to add some more options
#
###############################################################################################

'stretch_lite' = 'http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2018-11-15/2018-11-13-raspbian-stretch-lite.zip'

'stretch_desktop' = 'http://downloads.raspberrypi.org/raspbian/images/raspbian-2019-04-09/2019-04-08-raspbian-stretch.zip'

'motioneye_os' = 'https://github.com/ccrisan/motioneyeos/releases/download/20190911/motioneyeos-raspberrypi-20190911.img.xz'

'octoprint' = 'https://github.com/guysoft/OctoPi/releases/download/0.17.0/octopi-buster-lite-0.17.0.zip'

'dietpi' = 'https://dietpi.com/downloads/images/DietPi_RPi-ARMv6-Buster.7z'

'retropie' = 'https://github.com/RetroPie/RetroPie-Setup/releases/download/4.6/retropie-buster-4.6-rpi2_rpi3.img.gz'

'debian_daily' = 'https://raspi.debian.net/daily/raspi_3.img.xz'

'pi64_Beta' = 'https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2020-05-28/2020-05-27-raspios-buster-arm64.zip'

'buster_lite' = 'http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-09-30/2019-09-26-raspbian-buster-lite.zip'

'buster_desktop' = 'http://downloads.raspberrypi.org/raspbian/images/raspbian-2019-09-30/2019-09-26-raspbian-buster.zip'

'ubuntu_mate_64' = 'https://ubuntu-mate.org/raspberry-pi/ubuntu-mate-20.04-beta1-desktop-arm64+raspi.img.xz'

'ubuntu_mate_32' = 'https://ubuntu-mate.org/raspberry-pi/ubuntu-mate-20.04-beta1-desktop-armhf+raspi.img.xz'