###############################################################################################
# clipi shortcut toml #
###############################################################################################

'Burn a bootable disk image' = true
'image' = 'debian_daily'
'target_disk' = 'sdc'
