###############################################################################################
# clipi shortcut toml #
###############################################################################################

'Burn a bootable disk image' = true
'image' = 'ubuntu_server_pi4_64'
'target_disk' = 'sdc'
'verbatim' = true
